using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Flowamaz.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddWorkflowTemplates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "workflow_templates",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    slug = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    description = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: false),
                    category = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    is_official = table.Column<bool>(type: "boolean", nullable: false),
                    org_id = table.Column<Guid>(type: "uuid", nullable: true),
                    yaml_content = table.Column<string>(type: "text", nullable: false),
                    preview_image_url = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    install_count = table.Column<int>(type: "integer", nullable: false),
                    average_rating = table.Column<decimal>(type: "numeric(3,2)", nullable: false),
                    tags = table.Column<string>(type: "jsonb", nullable: false),
                    version = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    is_active = table.Column<bool>(type: "boolean", nullable: false),
                    review_status = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false),
                    deleted_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_workflow_templates", x => x.id);
                });

            migrationBuilder.InsertData(
                table: "workflow_templates",
                columns: new[] { "id", "average_rating", "category", "created_at", "created_by", "deleted_at", "description", "install_count", "is_active", "is_deleted", "is_official", "name", "org_id", "preview_image_url", "review_status", "slug", "tags", "updated_at", "updated_by", "version", "yaml_content" },
                values: new object[,]
                {
                    { new Guid("00000000-0000-0000-0002-000000000001"), 0m, "Finance", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, null, "Two-level purchase approval with a resubmission loop for rejected requests.", 0, true, false, true, "Purchase Approval", null, null, "approved", "purchase-approval", "[\"finance\",\"approval\",\"purchase\"]", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, "1.0.0", "apiVersion: flowamaz/v1\nkind: Workflow\nmetadata:\n  id: purchase-approval\n  name: \"Purchase Approval\"\n  description: \"Two-level purchase approval with a resubmission loop.\"\n  version: \"1.0.0\"\nspec:\n  trigger:\n    type: form\n  variables:\n    amount:\n      type: number\n      required: true\n    requester:\n      type: string\n      required: true\n  nodes:\n    - id: start\n      type: trigger\n      label: \"Purchase requested\"\n    - id: manager-approval\n      type: human-gate\n      label: \"Manager approval\"\n    - id: route-decision\n      type: router\n      label: \"Approved?\"\n    - id: finance-approval\n      type: human-gate\n      label: \"Finance approval\"\n    - id: create-po\n      type: action\n      label: \"Create purchase order\"\n    - id: notify-rejected\n      type: action\n      label: \"Notify requester of rejection\"\n    - id: done\n      type: end\n      label: \"Complete\"\n  edges:\n    - id: e1\n      from: start\n      to: manager-approval\n    - id: e2\n      from: manager-approval\n      to: route-decision\n    - id: e3\n      from: route-decision\n      to: finance-approval\n      via: approved\n    - id: e4\n      from: route-decision\n      to: notify-rejected\n      via: rejected\n    - id: e5\n      from: finance-approval\n      to: create-po\n    - id: e6\n      from: create-po\n      to: done\n    - id: e7\n      from: notify-rejected\n      to: done" },
                    { new Guid("00000000-0000-0000-0002-000000000002"), 0m, "HR", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, null, "Multi-step new-hire onboarding checklist with HR approval gates.", 0, true, false, true, "Employee Onboarding", null, null, "approved", "employee-onboarding", "[\"hr\",\"onboarding\",\"checklist\"]", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, "1.0.0", "apiVersion: flowamaz/v1\nkind: Workflow\nmetadata:\n  id: employee-onboarding\n  name: \"Employee Onboarding\"\n  description: \"Multi-step new-hire onboarding checklist with HR gates.\"\n  version: \"1.0.0\"\nspec:\n  trigger:\n    type: form\n  variables:\n    employeeName:\n      type: string\n      required: true\n    startDate:\n      type: string\n      required: true\n  nodes:\n    - id: start\n      type: trigger\n      label: \"New hire created\"\n    - id: provision-accounts\n      type: action\n      label: \"Provision accounts\"\n    - id: assign-equipment\n      type: action\n      label: \"Assign equipment\"\n    - id: hr-paperwork\n      type: human-gate\n      label: \"HR confirms paperwork\"\n    - id: manager-welcome\n      type: action\n      label: \"Schedule manager welcome\"\n    - id: done\n      type: end\n      label: \"Onboarding complete\"\n  edges:\n    - id: e1\n      from: start\n      to: provision-accounts\n    - id: e2\n      from: provision-accounts\n      to: assign-equipment\n    - id: e3\n      from: assign-equipment\n      to: hr-paperwork\n    - id: e4\n      from: hr-paperwork\n      to: manager-welcome\n    - id: e5\n      from: manager-welcome\n      to: done" },
                    { new Guid("00000000-0000-0000-0002-000000000003"), 0m, "HR", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, null, "Manager-approved leave request with a calendar update step.", 0, true, false, true, "Leave Request", null, null, "approved", "leave-request", "[\"hr\",\"leave\",\"approval\"]", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, "1.0.0", "apiVersion: flowamaz/v1\nkind: Workflow\nmetadata:\n  id: leave-request\n  name: \"Leave Request\"\n  description: \"Manager-approved leave request with a calendar update.\"\n  version: \"1.0.0\"\nspec:\n  trigger:\n    type: form\n  variables:\n    days:\n      type: number\n      required: true\n  nodes:\n    - id: start\n      type: trigger\n      label: \"Leave requested\"\n    - id: manager-approval\n      type: human-gate\n      label: \"Manager approval\"\n    - id: decision\n      type: router\n      label: \"Approved?\"\n    - id: update-calendar\n      type: action\n      label: \"Update calendar\"\n    - id: notify-declined\n      type: action\n      label: \"Notify declined\"\n    - id: done\n      type: end\n      label: \"Complete\"\n  edges:\n    - id: e1\n      from: start\n      to: manager-approval\n    - id: e2\n      from: manager-approval\n      to: decision\n    - id: e3\n      from: decision\n      to: update-calendar\n      via: approved\n    - id: e4\n      from: decision\n      to: notify-declined\n      via: declined\n    - id: e5\n      from: update-calendar\n      to: done\n    - id: e6\n      from: notify-declined\n      to: done" },
                    { new Guid("00000000-0000-0000-0002-000000000004"), 0m, "IT", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, null, "Triage, assign, resolve and close an IT support ticket.", 0, true, false, true, "IT Support Ticket", null, null, "approved", "it-support-ticket", "[\"it\",\"support\",\"ticket\"]", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, "1.0.0", "apiVersion: flowamaz/v1\nkind: Workflow\nmetadata:\n  id: it-support-ticket\n  name: \"IT Support Ticket\"\n  description: \"Triage, assign, resolve and close an IT support ticket.\"\n  version: \"1.0.0\"\nspec:\n  trigger:\n    type: webhook\n  variables:\n    priority:\n      type: string\n      required: true\n  nodes:\n    - id: start\n      type: trigger\n      label: \"Ticket created\"\n    - id: triage\n      type: action\n      label: \"Triage ticket\"\n    - id: assign\n      type: action\n      label: \"Assign to engineer\"\n    - id: resolve\n      type: human-gate\n      label: \"Engineer resolves\"\n    - id: close\n      type: action\n      label: \"Close ticket\"\n    - id: done\n      type: end\n      label: \"Closed\"\n  edges:\n    - id: e1\n      from: start\n      to: triage\n    - id: e2\n      from: triage\n      to: assign\n    - id: e3\n      from: assign\n      to: resolve\n    - id: e4\n      from: resolve\n      to: close\n    - id: e5\n      from: close\n      to: done" },
                    { new Guid("00000000-0000-0000-0002-000000000005"), 0m, "Legal", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, null, "Legal review gate followed by an e-signature placeholder step.", 0, true, false, true, "Contract Review", null, null, "approved", "contract-review", "[\"legal\",\"contract\",\"review\"]", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, "1.0.0", "apiVersion: flowamaz/v1\nkind: Workflow\nmetadata:\n  id: contract-review\n  name: \"Contract Review\"\n  description: \"Legal review gate followed by an e-signature placeholder.\"\n  version: \"1.0.0\"\nspec:\n  trigger:\n    type: form\n  variables:\n    counterparty:\n      type: string\n      required: true\n  nodes:\n    - id: start\n      type: trigger\n      label: \"Contract submitted\"\n    - id: legal-review\n      type: human-gate\n      label: \"Legal review\"\n    - id: decision\n      type: router\n      label: \"Approved?\"\n    - id: esign\n      type: action\n      label: \"Send for e-signature\"\n    - id: request-changes\n      type: action\n      label: \"Request changes\"\n    - id: done\n      type: end\n      label: \"Complete\"\n  edges:\n    - id: e1\n      from: start\n      to: legal-review\n    - id: e2\n      from: legal-review\n      to: decision\n    - id: e3\n      from: decision\n      to: esign\n      via: approved\n    - id: e4\n      from: decision\n      to: request-changes\n      via: changes\n    - id: e5\n      from: esign\n      to: done\n    - id: e6\n      from: request-changes\n      to: done" },
                    { new Guid("00000000-0000-0000-0002-000000000006"), 0m, "Finance", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, null, "Receipt upload, manager approval, then finance approval.", 0, true, false, true, "Expense Claim", null, null, "approved", "expense-claim", "[\"finance\",\"expense\",\"approval\"]", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, "1.0.0", "apiVersion: flowamaz/v1\nkind: Workflow\nmetadata:\n  id: expense-claim\n  name: \"Expense Claim\"\n  description: \"Receipt upload, manager approval, then finance approval.\"\n  version: \"1.0.0\"\nspec:\n  trigger:\n    type: form\n  variables:\n    amount:\n      type: number\n      required: true\n  nodes:\n    - id: start\n      type: trigger\n      label: \"Claim submitted\"\n    - id: upload-receipt\n      type: action\n      label: \"Attach receipt\"\n    - id: manager-approval\n      type: human-gate\n      label: \"Manager approval\"\n    - id: finance-approval\n      type: human-gate\n      label: \"Finance approval\"\n    - id: reimburse\n      type: action\n      label: \"Trigger reimbursement\"\n    - id: done\n      type: end\n      label: \"Complete\"\n  edges:\n    - id: e1\n      from: start\n      to: upload-receipt\n    - id: e2\n      from: upload-receipt\n      to: manager-approval\n    - id: e3\n      from: manager-approval\n      to: finance-approval\n    - id: e4\n      from: finance-approval\n      to: reimburse\n    - id: e5\n      from: reimburse\n      to: done" },
                    { new Guid("00000000-0000-0000-0002-000000000007"), 0m, "Operations", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, null, "Procurement workflow with three sequential approval levels.", 0, true, false, true, "Vendor Onboarding", null, null, "approved", "vendor-onboarding", "[\"operations\",\"vendor\",\"procurement\"]", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, "1.0.0", "apiVersion: flowamaz/v1\nkind: Workflow\nmetadata:\n  id: vendor-onboarding\n  name: \"Vendor Onboarding\"\n  description: \"Procurement workflow with three sequential approval levels.\"\n  version: \"1.0.0\"\nspec:\n  trigger:\n    type: form\n  variables:\n    vendorName:\n      type: string\n      required: true\n  nodes:\n    - id: start\n      type: trigger\n      label: \"Vendor submitted\"\n    - id: procurement-review\n      type: human-gate\n      label: \"Procurement review\"\n    - id: compliance-review\n      type: human-gate\n      label: \"Compliance review\"\n    - id: finance-review\n      type: human-gate\n      label: \"Finance review\"\n    - id: activate-vendor\n      type: action\n      label: \"Activate vendor record\"\n    - id: done\n      type: end\n      label: \"Complete\"\n  edges:\n    - id: e1\n      from: start\n      to: procurement-review\n    - id: e2\n      from: procurement-review\n      to: compliance-review\n    - id: e3\n      from: compliance-review\n      to: finance-review\n    - id: e4\n      from: finance-review\n      to: activate-vendor\n    - id: e5\n      from: activate-vendor\n      to: done" },
                    { new Guid("00000000-0000-0000-0002-000000000008"), 0m, "IT", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, null, "Detect, triage, escalate, resolve and run a post-mortem.", 0, true, false, true, "Incident Response", null, null, "approved", "incident-response", "[\"it\",\"incident\",\"response\"]", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, "1.0.0", "apiVersion: flowamaz/v1\nkind: Workflow\nmetadata:\n  id: incident-response\n  name: \"Incident Response\"\n  description: \"Detect, triage, escalate, resolve and run a post-mortem.\"\n  version: \"1.0.0\"\nspec:\n  trigger:\n    type: webhook\n  variables:\n    severity:\n      type: string\n      required: true\n  nodes:\n    - id: start\n      type: trigger\n      label: \"Incident detected\"\n    - id: triage\n      type: action\n      label: \"Triage severity\"\n    - id: severity-router\n      type: router\n      label: \"Escalate?\"\n    - id: escalate\n      type: action\n      label: \"Escalate to on-call\"\n    - id: resolve\n      type: human-gate\n      label: \"Resolve incident\"\n    - id: post-mortem\n      type: action\n      label: \"Schedule post-mortem\"\n    - id: done\n      type: end\n      label: \"Resolved\"\n  edges:\n    - id: e1\n      from: start\n      to: triage\n    - id: e2\n      from: triage\n      to: severity-router\n    - id: e3\n      from: severity-router\n      to: escalate\n      via: high\n    - id: e4\n      from: severity-router\n      to: resolve\n      via: low\n    - id: e5\n      from: escalate\n      to: resolve\n    - id: e6\n      from: resolve\n      to: post-mortem\n    - id: e7\n      from: post-mortem\n      to: done" },
                    { new Guid("00000000-0000-0000-0002-000000000009"), 0m, "Finance", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, null, "Customer-support review, finance approval, then payment trigger.", 0, true, false, true, "Customer Refund", null, null, "approved", "customer-refund", "[\"finance\",\"refund\",\"approval\"]", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, "1.0.0", "apiVersion: flowamaz/v1\nkind: Workflow\nmetadata:\n  id: customer-refund\n  name: \"Customer Refund\"\n  description: \"Customer-support review, finance approval, then payment trigger.\"\n  version: \"1.0.0\"\nspec:\n  trigger:\n    type: form\n  variables:\n    amount:\n      type: number\n      required: true\n  nodes:\n    - id: start\n      type: trigger\n      label: \"Refund requested\"\n    - id: cs-review\n      type: human-gate\n      label: \"Customer support review\"\n    - id: finance-approval\n      type: human-gate\n      label: \"Finance approval\"\n    - id: issue-refund\n      type: action\n      label: \"Trigger payment refund\"\n    - id: done\n      type: end\n      label: \"Refunded\"\n  edges:\n    - id: e1\n      from: start\n      to: cs-review\n    - id: e2\n      from: cs-review\n      to: finance-approval\n    - id: e3\n      from: finance-approval\n      to: issue-refund\n    - id: e4\n      from: issue-refund\n      to: done" },
                    { new Guid("00000000-0000-0000-0002-000000000010"), 0m, "Operations", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, null, "Periodic compliance review workflow driven by due dates.", 0, true, false, true, "Compliance Checklist", null, null, "approved", "compliance-checklist", "[\"operations\",\"compliance\",\"review\"]", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), null, "1.0.0", "apiVersion: flowamaz/v1\nkind: Workflow\nmetadata:\n  id: compliance-checklist\n  name: \"Compliance Checklist\"\n  description: \"Periodic compliance review workflow driven by due dates.\"\n  version: \"1.0.0\"\nspec:\n  trigger:\n    type: schedule\n  variables:\n    period:\n      type: string\n      required: true\n  nodes:\n    - id: start\n      type: trigger\n      label: \"Review period starts\"\n    - id: gather-evidence\n      type: action\n      label: \"Gather evidence\"\n    - id: reviewer-sign-off\n      type: human-gate\n      label: \"Reviewer sign-off\"\n    - id: file-report\n      type: action\n      label: \"File compliance report\"\n    - id: done\n      type: end\n      label: \"Complete\"\n  edges:\n    - id: e1\n      from: start\n      to: gather-evidence\n    - id: e2\n      from: gather-evidence\n      to: reviewer-sign-off\n    - id: e3\n      from: reviewer-sign-off\n      to: file-report\n    - id: e4\n      from: file-report\n      to: done" }
                });

            migrationBuilder.CreateIndex(
                name: "ix_workflow_templates_category",
                table: "workflow_templates",
                column: "category");

            migrationBuilder.CreateIndex(
                name: "ix_workflow_templates_is_official",
                table: "workflow_templates",
                column: "is_official");

            migrationBuilder.CreateIndex(
                name: "ix_workflow_templates_slug",
                table: "workflow_templates",
                column: "slug",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "workflow_templates");
        }
    }
}
