// <auto-generated />
using System;
using Flowamaz.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flowamaz.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlowAmazDbContext))]
    [Migration("20260524145712_InitialScaffold")]
    partial class InitialScaffold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.AiTokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FunctionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("function_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_id");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<int>("TokensInput")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_input");

                    b.Property<int>("TokensOutput")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_output");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_token_usage");

                    b.HasIndex("FunctionId", "CreatedAt")
                        .HasDatabaseName("ix_ai_token_usage_function_id_created_at");

                    b.HasIndex("OrgId", "CreatedAt")
                        .HasDatabaseName("ix_ai_token_usage_org_id_created_at");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_ai_token_usage_workspace_id_created_at");

                    b.ToTable("ai_token_usage");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.ModelCatalogue", b =>
                {
                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("HasVision")
                        .HasColumnType("boolean")
                        .HasColumnName("has_vision");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MaxContextTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_context_tokens");

                    b.PrimitiveCollection<string>("PlanAccess")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_access");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<bool>("SupportsJsonMode")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_json_mode");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_streaming");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ModelId")
                        .HasName("pk_model_catalogue");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_model_catalogue_provider");

                    b.ToTable("model_catalogue");

                    b.HasData(
                        new
                        {
                            ModelId = "claude-haiku-4-5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Claude Haiku 4.5",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 200000,
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "claude-sonnet-4-6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Claude Sonnet 4.6",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 200000,
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "claude-opus-4-6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Claude Opus 4.6",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 200000,
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "gpt-4o",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "GPT-4o",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 128000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "azure-openai",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "gpt-4o-mini",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "GPT-4o mini",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 128000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "azure-openai",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "gemini-2-0-flash",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Gemini 2.0 Flash",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 1000000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "google",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "gemini-1-5-pro",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Gemini 1.5 Pro",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 1000000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "google",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "moonshot-v1-128k",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Moonshot v1 128k",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 128000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "kimi",
                            SupportsJsonMode = true,
                            SupportsStreaming = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "moonshot-v1-32k",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Moonshot v1 32k",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 32000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "kimi",
                            SupportsJsonMode = true,
                            SupportsStreaming = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "mistral-large",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Mistral Large",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 128000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "mistral",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.OrgAiConfig", b =>
                {
                    b.Property<Guid>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FunctionOverridesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("function_overrides_json");

                    b.PrimitiveCollection<string>("ProvidersEnabled")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("providers_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<string>("WorkspaceLockedFunctions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("workspace_locked_functions");

                    b.HasKey("OrgId")
                        .HasName("pk_org_ai_configs");

                    b.ToTable("org_ai_configs");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.PlatformAiConfig", b =>
                {
                    b.Property<string>("FunctionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("function_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("KeySource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key_source");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_id");

                    b.PrimitiveCollection<string>("PlanAccess")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_access");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FunctionId")
                        .HasName("pk_platform_ai_configs");

                    b.ToTable("platform_ai_configs");

                    b.HasData(
                        new
                        {
                            FunctionId = "copilot",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-haiku-4-5",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "nl-yaml",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-sonnet-4-6",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "visual-input",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-sonnet-4-6",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "node-exec",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Byok",
                            ModelId = "claude-haiku-4-5",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "process-intel",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-haiku-4-5",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "help-assist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-sonnet-4-6",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "doc-parse",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-sonnet-4-6",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.WorkspaceAiBudget", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<DateTime?>("AlertSentAt80Pct")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alert_sent_at80pct");

                    b.Property<DateTime>("BudgetResetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("budget_reset_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsHardCapped")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hard_capped");

                    b.Property<long>("MonthlyTokenLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("monthly_token_limit");

                    b.Property<long>("TokensUsedThisMonth")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_used_this_month");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("WorkspaceId")
                        .HasName("pk_workspace_ai_budgets");

                    b.HasIndex("BudgetResetDate")
                        .HasDatabaseName("ix_workspace_ai_budgets_budget_reset_date");

                    b.ToTable("workspace_ai_budgets");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.WorkspaceAiConfig", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("ByokCredentialRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("byok_credential_refs_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FunctionOverridesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("function_overrides_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("WorkspaceId")
                        .HasName("pk_workspace_ai_configs");

                    b.ToTable("workspace_ai_configs");
                });
#pragma warning restore 612, 618
        }
    }
}
