// <auto-generated />
using System;
using Flowamaz.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flowamaz.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlowAmazDbContext))]
    [Migration("20260526040912_AddWorkflowSlaThreshold")]
    partial class AddWorkflowSlaThreshold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.AiTokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FunctionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("function_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_id");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<int>("TokensInput")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_input");

                    b.Property<int>("TokensOutput")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_output");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_token_usage");

                    b.HasIndex("FunctionId", "CreatedAt")
                        .HasDatabaseName("ix_ai_token_usage_function_id_created_at");

                    b.HasIndex("OrgId", "CreatedAt")
                        .HasDatabaseName("ix_ai_token_usage_org_id_created_at");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_ai_token_usage_workspace_id_created_at");

                    b.ToTable("ai_token_usage");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.ModelCatalogue", b =>
                {
                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("HasVision")
                        .HasColumnType("boolean")
                        .HasColumnName("has_vision");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MaxContextTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_context_tokens");

                    b.PrimitiveCollection<string>("PlanAccess")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_access");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_model_id");

                    b.Property<bool>("SupportsJsonMode")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_json_mode");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_streaming");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ModelId")
                        .HasName("pk_model_catalogue");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_model_catalogue_provider");

                    b.ToTable("model_catalogue");

                    b.HasData(
                        new
                        {
                            ModelId = "claude-haiku-4-5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Claude Haiku 4.5",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 200000,
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            ProviderModelId = "claude-haiku-4-5",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "claude-sonnet-4-6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Claude Sonnet 4.6",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 200000,
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            ProviderModelId = "claude-sonnet-4-6",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "claude-opus-4-6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Claude Opus 4.6",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 200000,
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            ProviderModelId = "claude-opus-4-6",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "gpt-4o",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "GPT-4o",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 128000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "azure-openai",
                            ProviderModelId = "gpt-4o",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "gpt-4o-mini",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "GPT-4o mini",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 128000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "azure-openai",
                            ProviderModelId = "gpt-4o-mini",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "o1-mini",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "o1-mini",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 128000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "azure-openai",
                            ProviderModelId = "o1-mini",
                            SupportsJsonMode = false,
                            SupportsStreaming = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "gemini-2-0-flash",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Gemini 2.0 Flash",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 1000000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "google",
                            ProviderModelId = "gemini-2.0-flash",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "gemini-1-5-pro",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Gemini 1.5 Pro",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 1000000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "google",
                            ProviderModelId = "gemini-1.5-pro",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "gemini-1-5-flash",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Gemini 1.5 Flash",
                            HasVision = true,
                            IsEnabled = true,
                            MaxContextTokens = 1000000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "google",
                            ProviderModelId = "gemini-1.5-flash",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "moonshot-v1-128k",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Moonshot v1 128k",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 128000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "kimi",
                            ProviderModelId = "moonshot-v1-128k",
                            SupportsJsonMode = true,
                            SupportsStreaming = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "moonshot-v1-32k",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Moonshot v1 32k",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 32000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "kimi",
                            ProviderModelId = "moonshot-v1-32k",
                            SupportsJsonMode = true,
                            SupportsStreaming = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "moonshot-v1-8k",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Moonshot v1 8k",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 8000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "kimi",
                            ProviderModelId = "moonshot-v1-8k",
                            SupportsJsonMode = true,
                            SupportsStreaming = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "mistral-large",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Mistral Large",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 128000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "mistral",
                            ProviderModelId = "mistral-large",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "mistral-medium",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Mistral Medium",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 32000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "mistral",
                            ProviderModelId = "mistral-medium",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = "mistral-nemo",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Mistral Nemo",
                            HasVision = false,
                            IsEnabled = true,
                            MaxContextTokens = 128000,
                            PlanAccess = "[\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "mistral",
                            ProviderModelId = "mistral-nemo",
                            SupportsJsonMode = true,
                            SupportsStreaming = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.OrgAiConfig", b =>
                {
                    b.Property<Guid>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FunctionOverridesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("function_overrides_json");

                    b.PrimitiveCollection<string>("ProvidersEnabled")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("providers_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<string>("WorkspaceLockedFunctions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("workspace_locked_functions");

                    b.HasKey("OrgId")
                        .HasName("pk_org_ai_configs");

                    b.ToTable("org_ai_configs");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.PlatformAiConfig", b =>
                {
                    b.Property<string>("FunctionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("function_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("KeySource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key_source");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_id");

                    b.PrimitiveCollection<string>("PlanAccess")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_access");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FunctionId")
                        .HasName("pk_platform_ai_configs");

                    b.ToTable("platform_ai_configs");

                    b.HasData(
                        new
                        {
                            FunctionId = "copilot",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-haiku-4-5",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "nl-yaml",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-sonnet-4-6",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "visual-input",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-sonnet-4-6",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "node-exec",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Byok",
                            ModelId = "claude-haiku-4-5",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "process-intel",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-haiku-4-5",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "help-assist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-sonnet-4-6",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FunctionId = "doc-parse",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            KeySource = "Platform",
                            ModelId = "claude-sonnet-4-6",
                            PlanAccess = "[\"community\",\"starter\",\"pro\",\"enterprise\"]",
                            Provider = "anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.WorkspaceAiBudget", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<DateTime?>("AlertSentAt80Pct")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alert_sent_at80pct");

                    b.Property<DateTime>("BudgetResetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("budget_reset_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsHardCapped")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hard_capped");

                    b.Property<long>("MonthlyTokenLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("monthly_token_limit");

                    b.Property<long>("TokensUsedThisMonth")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_used_this_month");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("WorkspaceId")
                        .HasName("pk_workspace_ai_budgets");

                    b.HasIndex("BudgetResetDate")
                        .HasDatabaseName("ix_workspace_ai_budgets_budget_reset_date");

                    b.ToTable("workspace_ai_budgets");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Ai.WorkspaceAiConfig", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("ByokCredentialRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("byok_credential_refs_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FunctionOverridesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("function_overrides_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("WorkspaceId")
                        .HasName("pk_workspace_ai_configs");

                    b.ToTable("workspace_ai_configs");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Analytics.WorkflowInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InsightType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("insight_type");

                    b.Property<Guid?>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_acknowledged");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_insights");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_workflow_insights_workflow_definition_id");

                    b.HasIndex("WorkspaceId", "IsAcknowledged", "CreatedAt")
                        .HasDatabaseName("ix_workflow_insights_workspace_id_is_acknowledged_created_at");

                    b.ToTable("workflow_insights");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Analytics.WorkflowMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AvgDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("avg_duration_ms");

                    b.Property<long?>("BottleneckAvgMs")
                        .HasColumnType("bigint")
                        .HasColumnName("bottleneck_avg_ms");

                    b.Property<string>("BottleneckNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bottleneck_node_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("P95DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("p95duration_ms");

                    b.Property<long>("P99DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("p99duration_ms");

                    b.Property<DateTime>("PeriodHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_hour");

                    b.Property<int>("RunsCancelled")
                        .HasColumnType("integer")
                        .HasColumnName("runs_cancelled");

                    b.Property<int>("RunsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("runs_completed");

                    b.Property<int>("RunsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("runs_failed");

                    b.Property<int>("RunsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("runs_total");

                    b.Property<int>("SlaBreachCount")
                        .HasColumnType("integer")
                        .HasColumnName("sla_breach_count");

                    b.Property<long?>("SlaThresholdMs")
                        .HasColumnType("bigint")
                        .HasColumnName("sla_threshold_ms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_metrics");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workflow_metrics_workspace_id");

                    b.HasIndex("WorkflowDefinitionId", "PeriodHour")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_metrics_workflow_definition_id_period_hour");

                    b.ToTable("workflow_metrics");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OrgUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_user_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("OrgUserId")
                        .HasDatabaseName("ix_refresh_tokens_org_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Platform.OrgUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsOrgOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_org_owner");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_org_users");

                    b.HasIndex("OrgId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_org_users_org_id_email");

                    b.ToTable("org_users");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Platform.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("billing_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataRegion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_region");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<DateTime>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_organisations_plan_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organisations_slug");

                    b.ToTable("organisations");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Platform.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("features");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Limits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceAnnualUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_annual_usd");

                    b.Property<decimal>("PriceMonthlyUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_monthly_usd");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_plans_slug");

                    b.ToTable("plans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Features = "{\"sso\":false,\"scim\":false,\"customConnectors\":false,\"auditLog\":false,\"apiAccess\":false,\"byom\":false,\"dataResidency\":false,\"cmek\":false,\"processIntelligence\":false,\"roiAnalytics\":false}",
                            IsActive = true,
                            IsPublic = true,
                            Limits = "{\"maxWorkspaces\":1,\"maxMembersPerWorkspace\":1,\"maxWorkflowDefinitions\":5,\"maxRunsPerMonth\":500,\"maxAiCallsPerMonth\":0,\"maxStorageGb\":1,\"runRetentionDays\":7,\"apiRateLimitPerMinute\":10,\"allowedAiProviders\":[\"anthropic\"]}",
                            Name = "Community",
                            PriceAnnualUsd = 0m,
                            PriceMonthlyUsd = 0m,
                            Slug = "community",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Features = "{\"sso\":false,\"scim\":false,\"customConnectors\":true,\"auditLog\":false,\"apiAccess\":true,\"byom\":false,\"dataResidency\":false,\"cmek\":false,\"processIntelligence\":false,\"roiAnalytics\":false}",
                            IsActive = true,
                            IsPublic = true,
                            Limits = "{\"maxWorkspaces\":3,\"maxMembersPerWorkspace\":10,\"maxWorkflowDefinitions\":20,\"maxRunsPerMonth\":5000,\"maxAiCallsPerMonth\":0,\"maxStorageGb\":10,\"runRetentionDays\":90,\"apiRateLimitPerMinute\":60,\"allowedAiProviders\":[\"anthropic\",\"azure-openai\",\"google\"]}",
                            Name = "Starter",
                            PriceAnnualUsd = 490m,
                            PriceMonthlyUsd = 49m,
                            Slug = "starter",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Features = "{\"sso\":false,\"scim\":false,\"customConnectors\":true,\"auditLog\":true,\"apiAccess\":true,\"byom\":false,\"dataResidency\":false,\"cmek\":false,\"processIntelligence\":true,\"roiAnalytics\":true}",
                            IsActive = true,
                            IsPublic = true,
                            Limits = "{\"maxWorkspaces\":10,\"maxMembersPerWorkspace\":50,\"maxWorkflowDefinitions\":0,\"maxRunsPerMonth\":50000,\"maxAiCallsPerMonth\":0,\"maxStorageGb\":50,\"runRetentionDays\":365,\"apiRateLimitPerMinute\":300,\"allowedAiProviders\":[\"anthropic\",\"azure-openai\",\"google\",\"kimi\",\"mistral\"]}",
                            Name = "Pro",
                            PriceAnnualUsd = 1990m,
                            PriceMonthlyUsd = 199m,
                            Slug = "pro",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Features = "{\"sso\":true,\"scim\":true,\"customConnectors\":true,\"auditLog\":true,\"apiAccess\":true,\"byom\":true,\"dataResidency\":true,\"cmek\":true,\"processIntelligence\":true,\"roiAnalytics\":true}",
                            IsActive = true,
                            IsPublic = false,
                            Limits = "{\"maxWorkspaces\":0,\"maxMembersPerWorkspace\":0,\"maxWorkflowDefinitions\":0,\"maxRunsPerMonth\":0,\"maxAiCallsPerMonth\":0,\"maxStorageGb\":0,\"runRetentionDays\":0,\"apiRateLimitPerMinute\":0,\"allowedAiProviders\":[\"anthropic\",\"azure-openai\",\"google\",\"kimi\",\"mistral\",\"byom\"]}",
                            Name = "Enterprise",
                            PriceAnnualUsd = 0m,
                            PriceMonthlyUsd = 0m,
                            Slug = "enterprise",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Platform.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("billing_cycle");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<decimal>("OvercapCapUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("overcap_cap_usd");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_subscriptions_org_id");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Platform.UsageAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AiCallsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("ai_calls_count");

                    b.Property<decimal>("AiCostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("ai_cost_usd");

                    b.Property<long>("ApiCallsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("api_calls_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MemberPeak")
                        .HasColumnType("integer")
                        .HasColumnName("member_peak");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("PeriodMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period_month");

                    b.Property<long>("RunsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("runs_count");

                    b.Property<long>("StorageBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_usage_aggregates");

                    b.HasIndex("OrgId", "PeriodMonth")
                        .IsUnique()
                        .HasDatabaseName("ix_usage_aggregates_org_id_period_month");

                    b.ToTable("usage_aggregates");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workflow.GateDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<string>("AssignedToEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("assigned_to_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("text")
                        .HasColumnName("decision_note");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeliveryChannel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("delivery_channel");

                    b.Property<string>("DeliveryError")
                        .HasColumnType("text")
                        .HasColumnName("delivery_error");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("delivery_status");

                    b.Property<Guid?>("EscalatedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("escalated_to");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("node_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_gate_decisions");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_gate_decisions_assigned_to");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_gate_decisions_expires_at");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_gate_decisions_workspace_id");

                    b.HasIndex("InstanceId", "NodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_gate_decisions_instance_id_node_id");

                    b.ToTable("gate_decisions");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workflow.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("created_by_method");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_version");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HealthScore")
                        .HasColumnType("integer")
                        .HasColumnName("health_score");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NlDescription")
                        .HasColumnType("text")
                        .HasColumnName("nl_description");

                    b.Property<long?>("SlaThresholdMs")
                        .HasColumnType("bigint")
                        .HasColumnName("sla_threshold_ms");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("YamlContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yaml_content");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definitions");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workflow_definitions_workspace_id");

                    b.HasIndex("WorkspaceId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_definitions_workspace_id_slug");

                    b.ToTable("workflow_definitions");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workflow.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("NodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("node_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_events");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workflow_events_workspace_id");

                    b.HasIndex("InstanceId", "OccurredAt")
                        .HasDatabaseName("ix_workflow_events_instance_id_occurred_at");

                    b.HasIndex("InstanceId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_events_instance_id_sequence_number");

                    b.ToTable("workflow_events");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workflow.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrentNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("current_node_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EnvironmentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("environment_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("SagaState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("saga_state");

                    b.Property<string>("SagaStrategy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("saga_strategy");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TriggerPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("trigger_payload");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("WorkerLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("worker_lease_expires_at");

                    b.Property<string>("WorkerLeaseId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("worker_lease_id");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_instances");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_instances_idempotency_key");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workflow_instances_workspace_id");

                    b.HasIndex("Status", "WorkerLeaseExpiresAt")
                        .HasDatabaseName("ix_workflow_instances_status_worker_lease_expires_at");

                    b.ToTable("workflow_instances");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workflow.WorkflowNodeState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_payload");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_at");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("node_type");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_node_states");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workflow_node_states_workspace_id");

                    b.HasIndex("InstanceId", "NodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_node_states_instance_id_node_id");

                    b.ToTable("workflow_node_states");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workflow.WorkflowVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sensitive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_variables");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workflow_variables_workspace_id");

                    b.HasIndex("InstanceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_variables_instance_id_name");

                    b.ToTable("workflow_variables");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workflow.WorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("branch_name");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("boolean")
                        .HasColumnName("is_production");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("message");

                    b.Property<string>("TagName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tag_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("YamlContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yaml_content");

                    b.HasKey("Id")
                        .HasName("pk_workflow_versions");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workflow_versions_workspace_id");

                    b.HasIndex("WorkflowDefinitionId", "CommitSha")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_versions_workflow_definition_id_commit_sha");

                    b.ToTable("workflow_versions");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("OrgId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_workspaces_org_id_slug");

                    b.ToTable("workspaces");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workspaces.WorkspaceApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scopes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_api_keys_key_hash");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workspace_api_keys_workspace_id");

                    b.ToTable("workspace_api_keys");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workspaces.WorkspaceEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_environments");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_environments_workspace_id_name");

                    b.ToTable("workspace_environments");
                });

            modelBuilder.Entity("Flowamaz.Core.Entities.Workspaces.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrgUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_members");

                    b.HasIndex("WorkspaceId", "OrgUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_members_workspace_id_org_user_id");

                    b.ToTable("workspace_members");
                });
#pragma warning restore 612, 618
        }
    }
}
